stages:
  split:
    cmd: python src/data/make_dataset.py data/raw_data data/processed_data
    deps:
    - data/raw_data/raw.csv
    - src/data/make_dataset.py
    outs:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
  normalize:
    cmd: python src/data/normalize_data.py data/processed_data data/processed_data
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - src/data/normalize_data.py
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
  gridsearch:
    cmd: python src/models/grid_search.py
    deps:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
    - src/models/grid_search.py
    outs:
    - models/best_params.pkl
