stages:
  split:
    cmd: python src/data/make_dataset.py data/raw_data data/processed_data
    deps:
    - data/raw_data/raw.csv
    - src/data/make_dataset.py
    outs:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
  normalize:
    cmd: python src/data/normalize_data.py data/processed_data data/processed_data
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - src/data/normalize_data.py
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
  gridsearch:
    cmd: python src/models/grid_search.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - params.yaml
    - src/models/grid_search.py
    outs:
    - models/best_params.pkl
  training:
    cmd: python src/models/train.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - models/best_params.pkl
    - params.yaml
    - src/models/train.py
    outs:
    - models/best_model.pkl
  evaluate:
    cmd: python src/models/evaluate.py
    deps:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/y_test.csv
    - models/best_model.pkl
    - src/models/evaluate.py
    outs:
    - data/prediction.csv
    metrics:
    - metrics/scores.json:
        cache: false
